# Generated by Django 3.0.7 on 2020-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
